name: bmi_calculator
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.2
  font_awesome_flutter: ^10.7.0

  # cupertino_icons: ^0.1.2
  # font_awesome_flutter: ^8.4.0
  # flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
